PROJECT	:=	Brainz
FLAGS	:=	-Wall -Wextra -Werror -std=c++98
FLAGS	:=	-std=c++98
CC		:=	c++ $(FLAGS)

FILES	:= main.cpp	Zombie.cpp randomChump.cpp newZombie.cpp


$(PROJECT):	$(FILES)
	$(CC)	-o $(PROJECT) $(FILES)
