FROM mcr.microsoft.com/devcontainers/universal:2-linux


#norminette installation
RUN pip install --upgrade pip setuptools
RUN pip install norminette


#valgrind installation
RUN apt-get install valgrind
